### ISSUE TITLE
file not found wspr_spots.txt

### ISSUE THREAD

**Issue by djbr1** [sstjohn/x6100-wspr#3]
error raised during execution

`FileNotFoundError: [Errno 2] No such file or directory: 'wspr_spots.txt'  `

manually "touched"  wspr_spots.txt in /root directory, error is gone

**Comment by sstjohn** [comment]
I don't quite understand how you would have ended up trying to upload spots without having first produced a spots file. Is this reproducible? Do you have a stack trace?

**Comment by djbr1** [comment]
Hi Saul,
sorry cannot find proper logs or stack trace, "iterm" terminal logs are garbled with non printable characters, also "vi" or "less" obfuscate previous lines

this is what I could find:
```[15.04.2022, 10:23:54.481 AM] Traceback (most recent call last):
[15.04.2022, 10:23:54.481 AM]   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
[15.04.2022, 10:23:54.485 AM]     self.run()
[15.04.2022, 10:23:54.485 AM]   File "/usr/local/lib/python3.10/threading.py", line 946, in run
[15.04.2022, 10:23:54.488 AM]     self._target(*self._args, **self._kwargs)
[15.04.2022, 10:23:54.495 AM]   File "/root/x6100-wspr-main/./spotter-loop.py", line 176, in decode_thread_main
[15.04.2022, 10:23:54.495 AM]     upload_spots(next_recording)
[15.04.2022, 10:23:54.495 AM]   File "/root/x6100-wspr-main/./spotter-loop.py", line 180, in upload_spots
[15.04.2022, 10:23:54.496 AM]     if os.path.getsize(spotfile) == 0:
[15.04.2022, 10:23:54.496 AM]   File "/usr/local/lib/python3.10/genericpath.py", line 50, in getsize
[15.04.2022, 10:23:54.498 AM]     return os.stat(filename).st_size
[15.04.2022, 10:23:54.498 AM] FileNotFoundError: [Errno 2] No such file or directory: 'wspr_spots.txt'
[15.04.2022, 10:23:59.989 AM] Recording WAVE '/tmp/220415_0824.wav' : Signed 16 bit Little Endian, Rate 12000 Hz, Mono
[15.04.2022, 10:24:36.860 AM] ^CAborted by signal Interrupt...```

It could be error happens if nothing was spotted and scheduled skip to another band kicks in. Just a guess

**Comment by sstjohn** [comment]
If nothing was spotted, wsprd should produce an empty all_spots.txt file.
`upload_spots` is called from the decode thread which is triggered by a
completed recording, so there should be something there for wsprd to
process even if it just creates an empty spots file.

If you just run wsprd from a shell on the box, do you get the usage
statement? Are you launching spotter-loop.py from /root?
